### PR TITLE
Feature refactor clients table

### PR DESCRIPTION
**Pull request by Dan1el71**
This pull request includes significant updates to the client management features in the application. The changes primarily focus on refactoring the client components, adding modals for adding and deleting clients, and improving the overall user interface and experience.

### Client Component Refactoring:
* [`src/app/app.routes.ts`](diffhunk://#diff-7d01226345966b27520a30fae71d6f3d17f54d3d06bcbc3f0dff4195fc7d9cfcL10-L15): Removed individual client routes and components for listing, adding, editing, deleting, and searching clients. [[1]](diffhunk://#diff-7d01226345966b27520a30fae71d6f3d17f54d3d06bcbc3f0dff4195fc7d9cfcL10-L15) [[2]](diffhunk://#diff-7d01226345966b27520a30fae71d6f3d17f54d3d06bcbc3f0dff4195fc7d9cfcL48-L54)

### Add Client Modal:
* [`src/app/componentes/sub-menu-dash-board/clientes/add-modal/add-modal.component.ts`](diffhunk://#diff-9ea995e7bdb4d9c93fdb4c502d305a95cb1d9ba8432e1f62c2357ed4e7283028R1-R104): Created a new `AddModalComponent` for adding clients with form validation and service integration.
* [`src/app/componentes/sub-menu-dash-board/clientes/add-modal/add-modal.component.html`](diffhunk://#diff-acdecfabfc722f985308b39c0ef44fda8503f10e26ba13818ae1b89985333f38R1-R78): Added HTML template for the add client modal with form controls and submission handling.
* [`src/app/componentes/sub-menu-dash-board/clientes/add-modal/add-modal.component.css`](diffhunk://#diff-3095553a9b2d41f6ac048b58622057a93ad29b9fdb2fa91fd907c7af3c3c8b68R1-R28): Styled the add client modal for better user experience.

### Delete Client Modal:
* [`src/app/componentes/sub-menu-dash-board/clientes/delete-modal/delete-modal.component.ts`](diffhunk://#diff-d514e777ba45d9a9ecc93a84b78baf7efc48ce86434c307379d15dc1102b8909R1-R72): Created a new `DeleteModalComponent` for deleting clients with confirmation and service integration.
* [`src/app/componentes/sub-menu-dash-board/clientes/delete-modal/delete-modal.component.html`](diffhunk://#diff-b656451daabb78de836f55f208abe7286fa6a6a98b212dd7a38bec41603dda02R1-R25): Added HTML template for the delete client modal with confirmation message.
* [`src/app/componentes/sub-menu-dash-board/clientes/delete-modal/delete-modal.component.css`](diffhunk://#diff-6283016bfd8ccfd35e497f63519eaa0e69d4893aa4bc30883c5830450495ece3R1-R34): Styled the delete client modal for better user experience.

### Editable Row Component:
* [`src/app/componentes/sub-menu-dash-board/clientes/editable-row/editable-row.component.html`](diffhunk://#diff-40cc9798600ac9cbb1f1d6a7967a464777a72da717cdbda3a71fdbff9b87e934R1-R66): Added HTML template for editing client details directly within a table row.
* [`src/app/componentes/sub-menu-dash-board/clientes/editable-row/editable-row.component.css`](diffhunk://#diff-7fa6fdf0a804d5d412878004b572f0666c7e92feb2829d8553311f029d3e1bb8R1-R17): Styled the editable row component for better user experience.

### Client Component Updates:
* [`src/app/componentes/sub-menu-dash-board/clientes/clientes.component.ts`](diffhunk://#diff-2d00d6b20c71968db756fbb217438dca2269a995b97e1d4292625358748f0a33L1-R49): Updated `ClientesComponent` to use pagination and handle client deletion and page changes.
* [`src/app/componentes/sub-menu-dash-board/clientes/clientes.component.html`](diffhunk://#diff-d7a0d226e51dd2b70e3527b7695f91127023babdcfb0060558845fc423838edcL1-L25): Updated HTML to integrate the new table component for displaying clients with pagination.

### CODE REVIEW

**Review by Dan1el71 — COMMENTED** [review]
👌

**Review by Camilo-845 — APPROVED** [review]
Joa que maquina ese Daniel, todo fino 👌

**Review by Camilo-845 — CHANGES_REQUESTED** [review]
Ya baje tu rama en mi repositorio local y probé unas cosas, también actualice la base de datos con los últimos cambios y base de datos igual

El error que tengo es este, en la búsqueda, doy a buscar no ocurre nada
image

En el backend pasa esto:

image
image


No se si solo me pasa a mi

**Review by Camilo-845 — APPROVED** [review]
El input de búsqueda solo funciona con números enteros

**Pull request merged**
